debug: true

server:
    port: 0
    contextPath: /api

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9999/uaa/oauth/token_key


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    
logging:
  level:
    ROOT: INFO
    org.springframework.web: WARN
    org.springframework.cloud: DEBUG

spring:
    datasource:
      name: qualtypes-datasource
      url: jdbc:oracle:thin:@ldap://vdlbldap05a:389/CSSFOEDV,cn=OracleContext
      username: FODEV04
      password: FODEV0499
      driver-class-name: oracle.jdbc.OracleDriver
      test-on-borrow: true
      validation-query: SELECT 1 FROM dual
    jpa:
      show-sql: true
      database: oracle
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        ddl-auto: none
        generate-ddl: false